name: Deploy to Custom Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Ajoutez les étapes spécifiques à votre configuration de déploiement ici
      # Par exemple, copiez les fichiers build vers le serveur ou exécutez une commande de déploiement personnalisée

      # Exemple d'étape pour déployer vers GitHub Pages (à adapter pour une autre plateforme)
      - name: Deploy to GitHub Pages
        run: |
          npm run build  # Construire votre application
          npx gh-pages -d build  # Déployer les fichiers build vers GitHub Pages


