name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le déploiement lors d'un push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Version de Node.js à utiliser

    - name: Install dependencies
      run: npm install  # Installe les dépendances du projet

    - name: Build project
      run: npm run build  # Commande pour construire votre projet

    - name: Deploy to GitHub Pages
      run: npx gh-pages -d build  # Commande pour déployer votre projet

    - name: Clean up
      run: npm run clean  # Commande pour nettoyer les fichiers temporaires si nécessaire


