name: Deploy to Custom Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Mettez à jour vers une version plus récente de Node.js

      - name: Remove old node_modules and package-lock.json
        run: |
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install --force  # Utilisez --force pour résoudre les problèmes de lien symbolique

      - name: Build application
        run: npm run build

      - name: Deploy to Custom Server
        run: |
          ssh user@server 'bash -s' < deploy.sh
